name: Unittest OCPs

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        compiler:
          - gcc

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up C++ compiler
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        cmake: true
        make: true

    - name: Install C++ dependencies
      run: |
        sudo apt-get install coinor-libipopt-dev -y
        sudo apt-get install cpputest -y

        git submodule update --init --recursive

        git clone https://gitlab.com/libeigen/eigen.git
        cd eigen
        git checkout 3.4
        mkdir build && cd build
        cmake .. && make -j4 && sudo make install && sudo ldconfig
        cd ../..

